# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Monday theme (jeocool edition)"
license = "MIT"
licenselink = "https://github.com/cyevgeniy/monday-theme/blob/master/LICENSE"
description = "just enough to render the damn frontpage"
homepage = "https://github.com/cyevgeniy/monday-theme"

tags = [
    "blog", 
    "personal",
    "minimal", 
    "clean",
    "simple", 
    "light",
    "fast",
]

features = ["blog", "featured-posts"]

[author]
  name = "Yevgeniy Chaban"
  homepage = "https://ychbn.com"
