baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = 'monday-theme'
paginate=5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Mr. John Doe"
  siteDescription = "Best site in the world"
  introTitle="Introduction"
  introBody = """Hello, this is my blog and my introduction message. Put
  here small description about yourself. It is also a good idea to put here
  your contact email or something like this."""

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'monokailight'
tabWidth = 4
